title: Javier Honduvilla Coto
description: > # this means to ignore newlines until "baseurl:"
  Javier Honduvilla Coto personal page
baseurl: ""
canonical_url: "https://hondu.co"

gosquared_token: 'GSN-583350-L'
permalink: /blog/:title
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

highlighter: rouge

gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- vendor
