title: Javier Honduvilla Coto
description: > # this means to ignore newlines until "baseurl:"
  Javier Honduvilla Coto personal page
baseurl: ""
url: ""

gosquared_token: 'GSN-583350-L'
permalink: /blog/:title
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

highlighter: rouge

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
